### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kevlened** [pypi/support#2343]
### PyPI Username

`browsertron`

### Reason for request

I don't have access to the email for the browsertron user anymore. Is it possible to use the email address associated with kevlened?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello. I'm able to verify that emails to that address are bouncing, however we cannot associate an email address with multiple accounts.

We still need to validate this request since the `browsertron` User has Owner privileges on a project. Please email support@pypi.org, referencing this issue, to proceed with verification and to provide another address to associate with the account.
