### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by csoja** [pypi/support#2447]
### PyPI Username

`ContinuumIO`

### Reason for request

https://pypi.org/user/ContinuumIO/ is listed as the maintainer for quite a few projects.  ContinuumIO is now Anaconda, Inc. (This change happened on Jun 28, 2017.)The email associated with ContinuumIO is a private email associated with a former employee of the company.  We'd like to recover the user, and then change the maintainer on those projects to AnacondaInc and associated with an anaconda.com email address. 
Thank you for your help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Hello @csoja. The most straight forward way for this to be accomplished is for you to proceed with a normal password reset, assuming the domain is still deliverable, the users email could be forwarded to the correct person?

Otherwise it does appear that there was a successful login to the account on the same day as this issue was filed. So whoever did that would be able to update the email address.

As a last resort, you can email support@pypi.org referencing this issue for alternative recovery options.

**Comment by csoja** [comment]
@ewdurbin Thank you for your help!  Though I'm not sure which email address is associated with it, I sent an email to who I thought it might be.  I'm encouraged that there was a recent successful login.   I will email support@pypi.org if I'm still blocked in another week or two.
