### ISSUE TITLE
Project Limit Request: ruff - 40 GB

### ISSUE THREAD

**Issue by charliermarsh** [pypi/support#2545]
### Project URL

https://pypi.org/project/ruff

### Does this project already exist?

- [X] Yes

### New limit

40 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Ruff is a Python linter and code transformation tool written in Rust. It's used by projects like FastAPI, Pandas, Airflow, and more. The first release was about five months ago.

### How large is each release?

~64 MB total.

Each release contains 15 wheels, each of which is about ~4 MB, with the exception of the macOS universal wheel, which is ~8MB.

### How frequently do you make a release?

Right now, we release once daily. However, I'd like to move to a weekly release schedule, with exceptions for hotfixes and other urgent patches. If we were to continue releasing daily, this would give us enough room for a year's worth of releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Wow, this might be the quickest I've seen someone reached this limit. Please be mindful of your release frequency and consider reducing the frequency of releases. :)

I've increased the limit to 20 GB on PyPI. Happy to revisit this as you approach this limit, please file a new issue if/when this is necessary.

**Comment by charliermarsh** [comment]
Thanks @pradyunsg, I really appreciate it.

**Comment by pradyunsg** [comment]
FWIW, the only reason I'm a bit tentative with a limit like 40 GB is that the only sort of projects that have usually needed that limit are really long running; like https://github.com/pypi/support/issues/2480 or https://github.com/pypi/support/issues/2479.

**Comment by charliermarsh** [comment]
I can totally understand why the answer would be no, but I thought it was worth asking: is there any way for me to pay to cover the costs of the hosting for Ruff? I can and will donate to the PSF, but I assume those donations aren't meant to be "transactional" in that way.

**Comment by pradyunsg** [comment]
I don't believe there is any way to provide earmarked donations like that.

Besides, I'm not sure if/how costs could be computed for something like this, since there's amortized costs, in-kind donations, volunteer labor and a US non-profit organisation involved. :)

The closest things to that are sponsoring the PyPA (https://github.com/sponsors/pypa/) or providing donations to PSF's Packaging-WG (https://donate.pypi.org/); both of which are more broadly focused at the entire Python packaging toolchain.

**Comment by ofek** [comment]
It might make sense to come up with a deletion strategy since the majority of releases over time would never be used nor pinned. Perhaps do a weekly/biweekly/monthly release that users would know never would be deleted, then every daily release delete after a month or two. You could probably get away with this by doing calendar versioning and the releases that would never be deleted would have the year and month, while the ephemeral daily releases would have an additional component.

**Comment by onerandomusername** [comment]
> It might make sense to come up with a deletion strategy since the majority of releases over time would never be used nor pinned. Perhaps do a weekly/biweekly/monthly release that users would know never would be deleted, then every daily release delete after a month or two. You could probably get away with this by doing calendar versioning and the releases that would never be deleted would have the year and month, while the ephemeral daily releases would have an additional component.

That could work, but there's no existing mechanism for telling projects that pin development requirements to not use an ephemeral release, unless ruff were to use beta/alpha/rc tags on those ephemeral releases. This would make them less likely to be pinned but they could still be installed like now if desired.
