### ISSUE TITLE
PEP 541 Request: pyNebula

### ISSUE THREAD

**Issue by cracker911181** [pypi/support#2570]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/pyNebula

### Your PyPI username

`USER_NAME`: https://pypi.org/user/cracker911181

### Reasons for the request

I upload my package named 'pyNebula' yesterday. But today when I loged in to my pypi account 
I noticed that my project was deleted. But I Don't get any notification. Please recover it....

When i trying to re-upload the package in show me this error:

ERROR HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
171 The name 'pyNebula' isn't allowed.

Please fix it and recover my project please as soon as possible.  @ewdurbin  @yeraydiazdiaz 

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/cracker911181/pyNebula

### Contact and additional research

I didn’t   contract anyone. Because that was my project. And now there are no project at this name. When I try to reupload my project. It show me to this error:

ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         The name 'pyNebula' isn't allowed.                   

Please recover my project. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by merwok** [comment]
First, don’t ask here and on the mailing-list and on unrelated tickets here.

Second, this obfuscated code was probably detected as malicious: https://github.com/cracker911181/pyNebula/blob/main/pyNebula/pyNebula.py

**Comment by cracker911181** [comment]
But It's an encoder pip only.

**Comment by cracker911181** [comment]
Please recover my project....  It's an python script encryptor. And It's Obfuscated on marshal

**Comment by cracker911181** [comment]
@merwok

**Comment by yeraydiazdiaz** [comment]
Please, stop tagging people and commenting on other issues, it will not help your request. We deal with them in batches in order of creation and when volunteers have time. Please be patient.

**Comment by cracker911181** [comment]
Okey.

**Comment by cracker911181** [comment]
But why did you remove my pip?

**Comment by ewdurbin** [comment]
@cracker911181 you need to stop spamming across forums, issues, mailing lists, and email addresses regarding this and other requests of yours. if you continue we'll begin blocking your account.

please be patient and a PyPI maintainer will review when they are able.

**Comment by cracker911181** [comment]
Okey. I am sorry🥺

**Comment by ewdurbin** [comment]
Hi @cracker911181, your project was removed from PyPI after being reported as a potentially malicious project due to obfuscated code that masks or hides underlying functionality.

After reviewing the code within the project [as uploaded](https://inspector.pypi.io/project/pynebula/0.9/packages/9c/2c/6cc2bdc01545f60438dbfff2dd7dd396f7cfe90d76b5d2e342d754e669c7/pyNebula-0.9.tar.gz/pyNebula-0.9/pyNebula/pyNebula.py) the PyPI administrator reviewing reports agreed with the reporters that the project was invalid per [PEP 541](https://peps.python.org/pep-0541/#invalid-projects). Specifically "project uses obfuscation to hide or mask functionality".

Such obfuscation is unnecessary for nearly all valid usecases, and is frequently used to further obfuscate other malicious software uploaded to PyPI.

Given the above, the original decision of the PyPI maintainer will remain and the PyNebula name will not be released for reuse on the index.

Please note that further uploads of similarly obfuscated software are likely to see the same reports, analysis, and decision.

Please also note that your behavior to try to gain attention by relentlessly spamming must also cease, or we will enforce blocks of your accounts across PyPI, Python, and Python Software Foundation services.

**Comment by cracker911181** [comment]
Thank you❤️. Please Don't mind. I have one question: can i encode my code with base64??

And sorry for today's activities😢
