### ISSUE TITLE
Project Limit Request: onnxruntime-gpu - 30 GB

### ISSUE THREAD

**Issue by faxu** [pypi/support#2641]
### Project URL

https://pypi.org/project/onnxruntime-gpu

### Does this project already exist?

- [X] Yes

### New limit

30GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We have hit the 10GB limit in our 1.14.1 release, which only contains partial files for the full release. 
Increasing limit by 20GB should support all future releases in the upcoming years. 

### How large is each release?

Each release is 1050MB, which contains builds for a number of different supported architectures as the product is cross-platform

### How frequently do you make a release?

About 5x a year. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @faxu :wave:
Looking at this release: https://pypi.org/project/onnxruntime-gpu/1.14.0/#files it seems that your project is a good candidate to get advantage of the Limited API https://docs.python.org/3/c-api/stable.html so in that case you end up having 1-wheel-per-platform, avoiding having wheels for different python versions.
I do understand that such modification before a release is a no-go, but please consider it for future ones, otherwise it's probable that your project will grow a lot in the next couple of years.

Would it be OK for you to double your current project size, from 10 to 20 G?

**Comment by faxu** [comment]
@cmaureir Yes, 20G is good for now, and we will look at the Limited API option!

**Comment by faxu** [comment]
@cmaureir any update on this?

**Comment by cmaureir** [comment]
Hey @faxu :wave:
sorry for the delay, long day at work :nerd_face: 
I've set the project limit for `onnxruntime-gpu` to 20 GB on PyPI. Please be mindful of the frequency of releases at that size, and check the limited api option.
have a nice end of the week :tada:
