### ISSUE TITLE
File Limit Request: rembg-aws-lambda - 250 MB

### ISSUE THREAD

**Issue by rnag** [pypi/support#2672]
### Project URL

https://pypi.org/project/rembg-aws-lambda

### Does this project already exist?

- [X] Yes

### New Limit

250 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

[rembg-aws-lambda](https://pypi.org/project/rembg-aws-lambda/) is a tool to remove images background.

The file size limit is due to AI/ML dependencies (mainly a single `.onnx` file)

I bundle a data file [u2net.onnx](https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx) in my project (~168MB). Source is here:
https://github.com/xuebinqin/U-2-Net

### Reasons for the request

The file size limit is due to AI/ML dependencies (mainly a single `.onnx` file). Source is here:
https://github.com/xuebinqin/U-2-Net

I don't foresee the release size or total project size to increase in the future. The buffer space is in case additional (smaller sized) `*.onnx` files would be included in future releases.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @rnag :wave: Thanks for the description.
I've set the upload limit for `rembg-aws-lambda` to 300 MB on PyPI, however I couldn't do the same on TestPyPI because the project doesn't exist. In case you still want that, please open a new report.
 Please be mindful of the frequency of releases at that size.
have a nice Sunday!

**Comment by rnag** [comment]
Thank you! Cheers, and a happy Monday 😄
