### ISSUE TITLE
File Limit Request: acid-chess - 500 MB

### ISSUE THREAD

**Issue by ierror** [pypi/support#2692]
### Project URL

https://pypi.org/project/acid-chess/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

The installation process of the chess computer should be as simple as possible for the users. Unfortunately, the models for board recognition and squares classification already need 700MB uncompressed. 

I had already tried a "binary" release, but due to the packages used (PyTorch etc.) it is extremely difficult to bundle a cross-platform release with python.

### Reasons for the request

Background:
https://github.com/ierror/acid-chess

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Have you explore with a method to download the models? NLTK has a simple approach that when you attempt to do something it points to a command to download the data: https://www.nltk.org/install.html#installing-nltk-data 
If you expect people to have the working UI, then maybe you could display a dialog with a message to download the model instead with a click.

The motivation of finding a solution like that, is because the moment you get 500M the project limit will be reached really fast and then you will have a more complicated scenario to ask for the amount of GB for the pypi project.
Let me know!

**Comment by di** [comment]
Closing due to lack of response.
