### ISSUE TITLE
File Limit Request: FBI_ DEBSCHL- 500 MB

### ISSUE THREAD

**Issue by debmeute** [pypi/support#2734]
### Project URL

https://test.pypi.org/simple/fbi-debschl

### Does this project already exist?

- [X] Yes

### New Limit

500 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

TestPyPI

### About the project

This is an university project. We are asked to construct an GUI that will create robot portrait according to the choices of a person (such as in the case of a victim that will try to reconstruct the face of its agressor). To do so we need models that will encode the picture to do mutation over them.

### Reasons for the request

The project now requires models that are already compressed to reduce the size however we can't decrease more the size of the models used for the creation of an autoencoder. Plus the models requires a certain amount of pictures that also have a minimum size that can't be decreased.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Have you explore other ways of getting the model rather than include them in the wheel? other projects have provide a module method `.download()` so they can fetch it from a custom URL.
Does the model change with each release? you could even have a dependency on another package that just contains the model.

**Comment by di** [comment]
Closing due to lack of response.
