### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by SheshankJoshi** [pypi/support#2749]
### PyPI Username

sheshankjoshi

### Reason for request

My mobile device having my 2FA has crashed and needed complete reset. Unfortunately, the authentication used was Google Authenticator, which lost all else in my account. 
I still have access to the email address used for registration. 
Recovery codes are also lost when my data was deleted by mistake. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
