### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by 2Bor3d** [pypi/support#2750]
### PyPI Username

2_Bored

### Reason for request

I forgot what i set up as my second factor. I think i used google authenticator but i have nothing saved there, maybe it wasn't transferred when i switched devices. I still have access to my email address and would like to authenticate using that way but i didn' find any way to do that on your website.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
