### ISSUE TITLE
PEP 541 Request: dbt-athena

### ISSUE THREAD

**Issue by nicor88** [pypi/support#2759]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/dbt-athena/

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nicor88/

### Reasons for the request

I'm one of the maintainer of [dbt-athena](https://github.com/dbt-athena/dbt-athena) a dbt adapter for AWS athena.

Historically there have being quite some AWS athena adatpers out there, but the latest fork is more community based, as we have a group of core maintainers (5) and many contributors. 

Currently we publish the pypi wheels to https://pypi.org/project/dbt-athena-community/ but as there are many adapters, the confusing is high and we would like to claim the usage of `dbt-athena`.

https://pypi.org/project/dbt-athena/ somehow looks not maintained.

### Maintenance or replacement?

Maintenance

### Source code repositories URLs

The new source code repository can be find at [dbt-athena](https://github.com/dbt-athena/dbt-athena), 

The original source repo seems to be https://github.com/Dandandan/dbt-athena (as you can read they say explicitly to switch to the another Fork, https://github.com/Tomme/dbt-athena/ that's where we fork from in November 2022, and also that one is not maintained anymore.

### Contact and additional research

I contacted the author `[Lucas Saletti](mailto:lucas.saletti92@gmail.com)` by email, but I didn't receive any answer.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by nicor88** [comment]
@encukou any chance that you could look into the above? I opened the issue ~1 year ago, but now is still relevant.

cc @dataders

**Comment by encukou** [comment]
Sorry, I am not an admin here, and I have strict instructions about what I can do on this repo.

**Comment by nicor88** [comment]
@encukou thanks for coming back to us. Could you point us to who we can escalate this issue? 🙏🏻

**Comment by nicor88** [comment]
@ewdurbin sorry for the ping here, we would like to move forward with this request, not sure who to ping, but I saw that you merged a recent [commit](https://github.com/pypi/support/pull/3877). 
As note, I tried to reach out to the maintainers, specifically [lsaletti](https://pypi.org/user/lsaletti/), but somehow after multiple pings (via Linkedin) I didn't received any answer.

Also, as possible to see [here](https://pypi.org/project/dbt-athena/), the maintainer state that the project is currently not maintained.

**Comment by encukou** [comment]
We are working to contact the owner to determine if they're reachable.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.

**Comment by nicor88** [comment]
@encukou thanks for the message, I believe that there is quite some unclarity here.

https://pypi.org/project/dbt-athena/ is the pypi published version of https://github.com/Tomme/dbt-athena/, as you can see from the pypi project description. But the point here is that https://pypi.org/project/dbt-athena/ is not maintaned by the same person that used to maintain https://github.com/Tomme/dbt-athena/.
At the same time https://github.com/Tomme/dbt-athena/ is published into https://pypi.org/project/dbt-athena-adapter/.

Therefore I don't understand why the maintainer of dbt-athena in pypi mentioned that.

@encukou I can try to reach out, how did you reach out the person? Thanks - I tried via the email in the pypi project but I was not successful.

**Comment by dataders** [comment]
@encukou really appreciate your help here! Did you hear from Lucas Saletti (PyPI maintainer) or In an attempt to clarify for posterity, I made the below table of all the relevant information.


Did you hear from Lucas Saletti the owner of PyPI project, `dbt-athena`? Or did you hear from Daniël Herës, maintainer of the corresponding GitHub repo? Or someone else?

If it was Lucas, their answer is challenging because they don't have merge rights on the repo, so their offer is rather empty.

| GitHub repo                                                       | first commit | last commit                                                                                                          | GitHub maintainer                                         | PyPI project                                                          | PyPI latest version                                                            | PyPI maintainer(s)                                                                                                                                      |
| ----------------------------------------------------------------- | ------------ | -------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- | --------------------------------------------------------------------- | ------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [dbt-labs/dbt-presto](https://github.com/dbt-labs/dbt-presto)     | Jan 19, 2020 | Jan 19, 2020 ([`a32f92e`](https://github.com/dbt-labs/dbt-presto/commit/8380c05a74d245013273d39898c8172126537046))   | [@drewbanin](https://github.com/drewbanin) (Drew Banin)   | [dbt-presto](https://pypi.org/project/dbt-presto)                     | [`0.21.1` (Nov 29 2021)](https://pypi.org/project/dbt-presto/0.21.1/)          | dbt Labs ([`fishtown-analytics`](https://pypi.org/user/fishtown-analytics/) info@fishtownanalytics.com)                                                 |
| [Dandandan/dbt-athena](https://github.com/Dandandan/dbt-athena)   | (above)      | Jan  7, 2021 ([`65f370d`](https://github.com/Dandandan/dbt-athena/commit/65f370d166fcdfe1143b7f2e601bc3570a95d3c6))  | [@Dandandan](https://github.com/Dandandan) (Daniël Heres) | [dbt-athena](https://pypi.org/project/dbt-athena)                     | [`0.0.5` (Mar 24, 2021)](https://pypi.org/project/dbt-athena/0.0.5/)           | Lucas Saletti ([`lsaletti`](https://pypi.org/user/lsaletti/) lucas.saletti92@gmail.com) Marcelo Santino ([`msantino`](https://pypi.org/user/msantino/)) |
| [Tomme/dbt-athena](https://github.com/Tomme/dbt-athena)           | (above)      | Aug  8, 2022 ([`83f7756`](https://github.com/Tomme/dbt-athena/commit/83f775643ab6e1edea605bc3f187ef28c2d20947))      | [@Tomme](https://github.com/Tomme)                        | [dbt-athena-adapter](https://pypi.org/project/dbt-athena-adapter)     | [`1.0.1` (Aug 8, 2022)](https://pypi.org/project/dbt-athena-adapter/1.0.1/)    | Thomas Elvey ([`Tomme`](https://pypi.org/user/Tomme/) tomelvey@googlemail.com)                                                                          |
| [dbt-athena/dbt-athena](https://github.com/dbt-athena/dbt-athena) | (above)      | Aug 23, 2024 ([`9b79444`](https://github.com/dbt-athena/dbt-athena/commit/9b794449b9f97a6aa6e6a2d110f7e65fe13c71a6)) | [@nicor88](https://github.com/nicor88)                    | [dbt-athena-community](https://pypi.org/project/dbt-athena-community) | [`1.8.3` (Jun 27, 2024)](https://pypi.org/project/dbt-athena-community/1.8.3/) | Nicola Corda ([`nicor88`](https://pypi.org/user/nicor88/) )                                                                                             |

**Comment by encukou** [comment]
I heard from Lucas Saletti.


If the project is malware or dangerous, you can “report the project as malware” at https://pypi.org/project/dbt-athena/.
If the project infringes on your intellectual property, e-mail legal@python.org (as per PEP 541).
If it's just an inactive project, I can't recommend to transfer it against the current owner's wishes. I realize that the offer is empty and ambiguous, but that's unfortunately not relevant to the PEP-541 process :(

Since you requested escalation, I'll re-open this issue, and leave to the admins to reconsider. Unfortunately, that might take some time.

**Comment by encukou** [comment]
The owner responded to our email and said we should transfer the project,
so we recommend that the PyPI Administrators assign nicor88 as the new
owner of dbt-athena.

**Comment by amychen1776** [comment]
@encukou the new owner should come over to dbt labs. @nicor88 has transferred ownership to us for the related git project.

**Comment by encukou** [comment]
After the admins do the transfer, nicor88 can add more owners. I see @nicor88 as an owner on dbt-athena-community so I assume you can trust them :)

**Comment by ewdurbin** [comment]
Added 'nicor88' as 'Owner' on 'dbt-athena'

**Comment by colin-rogers-dbt** [comment]
@ewdurbin can we also transfer the test.pypi repository? https://test.pypi.org/project/dbt-athena/

cc: @nicor88

**Comment by ewdurbin** [comment]
Done.
