### ISSUE TITLE
Project Limit Request: leadtoolspynet - 750MB

### ISSUE THREAD

**Issue by LEADTOOLSSupport** [pypi/support#2826]
### Project URL

None yet. Cannot upload

### Does this project already exist?

- [X] Yes

### New limit

750MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

The project is the Python wrapper for the renowned LEADTOOLS SDK (https://www.leadtools.com/), which has been a professional and reliable software development kit in the market for over 30 years. In 2023, we are expanding the SDK's platform support, which currently includes .NET, Java, JavaScript, Android, and Apple, to encompass Python as well. Our goal is to upload a Wheel package containing the necessary wrappers, enabling developers to effortlessly install and utilize our Python binaries directly from PyPI.

### How large is each release?

~650MB total

The Wheel package is designed to be cross-platform, including binaries for various operating systems, which accounts for its larger size.

### How frequently do you make a release?

Once or twice a year

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @LEADTOOLSSupport :wave:
please upload an empty release so the project exists on PyPi, you can do an empty 0.0 release for example.

Due to the nature of the package, it might be a better option to explore splitting the project into a couple of wheels, so you have a dependency depending on the modules, or whatever other functionality you have. A 650M wheel is certainly a large package, and you might reach the project limit soon.

**Comment by LEADTOOLSSupport** [comment]
Hello @cmaureir!

I've uploaded a shell of our package to pypi:
https://pypi.org/project/leadtools/

Thanks,
Hadi

**Comment by LEADTOOLSSupport** [comment]
Has there been any progress on this issue?

**Comment by di** [comment]
I've set the upload limit for `leadtoolspynet` to 750 MB on PyPI and TestPyPI. Please be mindful of the frequency of releases at that size.
