### ISSUE TITLE
File Limit Request:  nvidia_dali_cuda110- 550 MB

### ISSUE THREAD

**Issue by JanuszL** [pypi/support#2832]
### Project URL

https://pypi.org/project/nvidia_dali_cuda110

### Does this project already exist?

- [X] Yes

### New Limit

550 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Part of Nvidia component Dali

### Reasons for the request

The new wheel size exceeds existing limit i.e. 100 MB. In future too we might see increase in the size.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @JanuszL :wave:
The project doesn't exist on testpypi, so if you want an increase there, please submit  a new request once you create it.

I've set the upload limit for `nvidia_dali_cuda110` to 550 MB on PyPI. Please be mindful of the frequency of releases at that size, because you might reach the project limit quicker.

Have a nice week :tada:

**Comment by JanuszL** [comment]
Thanks!
Many thanks for it.
