### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by rffontenelle** [pypi/support#2853]
### PyPI Username

`rffontenelle`

### Reason for request

I lost access to my 2FA app and I don't have a recovery code. To be honest, I haven't used much my account as I created it to test pypa/warehouse translation, but I would like to recover access to it since it is linked with my personal email. Thanks in advance.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by rffontenelle** [comment]
Thanks a lot!
