### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Robbankz** [pypi/support#2868]
### PyPI Username

MrPerfect4949

### Reason for request

lost account access after getting new phone cant access gmail or python accounts, it isnt you guys at pypi its those idiots at Google screwing the internet up adding new user unfriendly bullshit (excuse my blunt truth), now when you get a new phone with the same number you had all your life, you gotta go through flaming hoops of nonsense to access a normal account, no suspicious activity, no scams coming from my way, all for a irritating company who shouldnt be as omnipresent as Google is anyway,somebody besides Mozilla needs to stand up those diabolical people over there at Alphabet

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
