### ISSUE TITLE
PEP 541 Request: pybot

### ISSUE THREAD

**Issue by imandr** [pypi/support#2877]
### Project to be claimed

`pybot`: https://test.pypi.org/project/pybot/

### Your PyPI username

`igorvm`: https://pypi.org/user/igorvm

### Reasons for the request

I would like to use the name for a project. There is the project with that name in the test instance, but not in production.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

Existing pybot: https://github.com/ben-cunningham/python-messenger-bot.git

My project: https://github.com/imandr/pythreader.git

### Contact and additional research

I have contacted the authors Benjamin Cunningham and Austin Hendy by email on 2/16/2023 but never heard back from them.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by imandr** [comment]
Any progress on this issue ?

**Comment by encukou** [comment]
For the test PyPI, projects are generally reassigned to the owner on the production PyPI instance.
However, https://pypi.org/project/pybot/ exists since 2013, and is owned by `@TommehM`, not `@igorvm`. 

Could you clarify which name you want? If it's pybot on test.pypy.org, I can't recommend transferring it to you.

Disclaimer: We are providing support to the PyPI Administrators to validate
this request and make a recommendation on the outcome and actions to be
taken. Final determination will be made by the PyPI Administrators when our
process is complete.
