### ISSUE TITLE
Project Limit Request: aws-cdk.lambda-layer-kubectl-v24 - 100 GB

### ISSUE THREAD

**Issue by RomainMuller** [pypi/support#2935]
### Project URL

https://pypi.org/project/aws-cdk.lambda-layer-kubectl-v24

### Does this project already exist?

- [X] Yes

### New limit

100

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

It is a component package for the AWS CDK v2 that contains code that backs an AWS Lambda layer for IaC (if not in this package, the content would be include in the AWS CDK v2 package instead, which only moves the weight around, doesn't actually reduce it).

The package is released frequently to include any security updates to the provided lambda layer, which contains the `kubectl` tools as quickly as possible, as the risk profile for this tool is quite high.

### How large is each release?

Each release is approximately 30MiB in size, and this project is released daily. The bulk of the weight of the package is a data artifact that needs to be shipped to AWS CDK customers.

We are considering reducing the publication frequency for this package (daily -> weekly), but would still require a limit increase for the project, as releases would continue adding up.

### How frequently do you make a release?

Daily. We are considering reducing this at the moment.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @RomainMuller :wave:
requesting 100G is really a long jump from 10G and will put your project into the top 20 https://pypi.org/stats/

Have you explored other options, like maybe split the current wheel into another package containing code that doesn't change much? Daily releases for sure are really a lot, and for weekly will still allow you to have 1.5G release per year, which still would make an increase from 10G to 20G still enough for a few years. Would that be an option for you?

Have a nice rest of the week!

**Comment by rix0rrr** [comment]
HI @cmaureir,

Thanks for responding. Turns out this package was releasing non-updates due to faulty automation. I've disabled that, we should now only be releasing real updates which are probably few and far between.

To make sure I got the automation right (which I'm like 99% sure of, but let's test it in a sensible way anyway 😅), could you raise the quota to 11 GB?

I'm pretty sure we shouldn't ever hit that anymore with the new config, and if we do because I messed up and forgot to check back on this, at least we've only wasted 1GB of disk space and not another 10.

Cheers!

**Comment by cmaureir** [comment]
Hey @rix0rrr :wave: I raised the project limit to 15G on PyPI. Thanks for your research, and in case you find another issue in the future maybe you can open a new issue.
Have a nice rest of the week :tada:
