### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by sweatylobster** [pypi/support#2948]
### PyPI Username

`sweatylobster`

### Reason for request

Hello!
My old phone I used for 2FA is broken beyond repair. I'd really like to publish a package, but am held back by my inability to authenticate via 2FA. Alas. I'd like to proceed, so here I am!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
