### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by jooyoungseo** [pypi/support#2975]
### PyPI Username

jooyoungseo

### Reason for request

I have recently changed my phone, but it failed to back up my 2-factor authentication data. I unfortunately did not save my recovery code on disk. Please help me initialize the 2-factor setup and access my account. If possible, please also help me recover my py test account access as well. I use the same ID.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
