### ISSUE TITLE
PEP 541 Request: jinja22

### ISSUE THREAD

**Issue by davidism** [pypi/support#3042]
### Project to be claimed

`jinja22`: https://pypi.org/project/jinja22

### Your PyPI username

`davidism`: https://pypi.org/user/davidism

### Reasons for the request

https://pypi.org/project/jinja22/ is a typo of https://pypi.org/project/jinja2/. Looks like it was mistakenly uploaded as a test, and should be deleted.

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/pallets/jinja

### Contact and additional research

Typo package does not indicate source link, and user does not have associated public email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by Thespi-Brain** [comment]
Hi @davidism,

We are working to contact the owner to determine if they're reachable and have sent them a courtesy message.

Final determination regarding project ownership will be made by the PyPI Administrators when the research process is complete.

**Comment by Thespi-Brain** [comment]
The owner(s) of project **jinja22** have gotten back to me and have ok'ed the removal of this project since they don't intend to add functionality to it. Per the PEP 541 policy, this project is deemed invalid and I recommend that the PyPI Admins delete the project and release the name for future use.

**Comment by miketheman** [comment]
Prohibited Project Name 'jinja22'
