### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by equalent** [pypi/support#3074]
### PyPI Username

`equalent`

### Reason for request

Lost 2FA authentication. Please help me recover access to my PyPI account as I set up 2FA a long time ago and have no means of restoring access myself at this point.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
