### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ashm-tech** [pypi/support#3171]
### PyPI Username

ashm-tech

### Reason for request

I have changed the phone on which there was an application for passing 2FA, and therefore I do not have access to the key that is generated on the old phone, and on the new one there is no data about my account to generate the key. Here are my details:
email: abdulaev-sh-m@outlook.com
Application: Microsoft Authenticator

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
User `ashm-tech` has valid recovery codes generated as of 2023-09-03 14:03:20.936598.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
