### ISSUE TITLE
File Limit Request: Sling - 150MB

### ISSUE THREAD

**Issue by flarco** [pypi/support#3209]
### Project URL

https://pypi.org/project/sling/

### Does this project already exist?

- [X] Yes

### New limit

150MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Sling is a CLI tool that extracts data from a source storage/database and loads it in a target storage/database. The python package is actually a wrapper around the original tool made in GoLang. So the binaries are embedded in the pypi package upon release.

I don't foresee requesting more size increases in the near future. The package has been bordering 100MB for a while now, and has just passed this threshold due to code updates. It's at 101MB now. I am requesting 150MB as a large buffer.

See release workflow here: https://github.com/slingdata-io/sling-python/blob/main/.github/workflows/release.yml
See setup.py here: https://github.com/slingdata-io/sling-python/blob/main/setup.py

### How large is each release?

101MB currently.

1 Linux binary.
1 Mac binary.
1 Windows binary.

### How frequently do you make a release?

Roughly 1-3 times a month.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Hi @flarco!

I'm guessing you've used the wrong template here -- did you mean to request a [per-file (in MBs)](https://github.com/pypi/support/issues/new?assignees=&labels=limit+request&projects=&template=limit-request-file.yml&title=File+Limit+Request%3A+PROJECT_NAME+-+000+MB) increase instead of the [overall project size (in GBs)](https://github.com/pypi/support/issues/new?assignees=&labels=limit+request&projects=&template=limit-request-project.yml&title=Project+Limit+Request%3A+PROJECT_NAME+-+00+GB)?

If so, please retitle this issue to have the right numbers and one of the relevant people will come around to it. :)

**Comment by flarco** [comment]
@pradyunsg Ah, thanks. Nutty I had put 150GB! :D
I meant 150MB limit per file. I fixed the Title.

**Comment by pradyunsg** [comment]
Neato! I've updated the per-file size limit for `sling` to 200 MiB on pypi.org. :)

As a heads up: This project is at 9.5 GiB / 10 GiB on the total project size limit, in case you want to file a separate issue for that too.

**Comment by flarco** [comment]
Thanks!
