### ISSUE TITLE
Project Limit Request: perspective-python - 30 GB

### ISSUE THREAD

**Issue by timkpaine** [pypi/support#3242]
### Project URL

https://pypi.org/project/perspective-python/

### Does this project already exist?

- [X] Yes

### New limit

30

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Perspective is a C++ data engine which distributes extensions, as well as web assets for Jupyterlab. 

### How large is each release?

~30MB including the extensions and the JavaScript assets. 

### How frequently do you make a release?

Once or twice a month.

We have just gone through and deleted all releases <1.0, but we'd like to have some extra room so we can keep a year or two of previous releases to avoid disrupting users.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by timkpaine** [comment]
@cmaureir  sorry to @ you directly, I noticed you took care of one of these last week, is it possible to look into this? It is blocking our release and we're going to have to delete ~20 more versions.

**Comment by cmaureir** [comment]
Hey @timkpaine :wave: no worries, I understand that time to time this issues are something that block us, or can  make us feel a bit unease when the issue is not solved.

I have set the project limit for `perspective-python` to 30G on PyPI, but please consider other ways to distribute the data of your packages, and maybe explore either a way to reduce the number of wheels, or split the wheel into a couple, so people can get some of the resources.

Have a nice week

**Comment by timkpaine** [comment]
Thanks @cmaureir!
