### ISSUE TITLE
Project Limit Request: tf-nightly-tpu - 36 GB

### ISSUE THREAD

**Issue by kanglant** [pypi/support#3253]
### Project URL

https://pypi.org/project/tf-nightly-tpu

### Does this project already exist?

- [X] Yes

### New limit

36 GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

tf-nightly-tpu is project for TensorFlow nightly builds on TPUs.

TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices.

Originally developed by researchers and engineers from the Google Brain team within Google's AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains. TensorFlow is licensed under [Apache 2.0](https://github.com/tensorflow/tensorflow/blob/master/LICENSE).

### How large is each release?

~1200 MB total.

Each Linux wheel has ~300 MB. 

We support 4 Python versions (3.9~3.12) in parallel. 

### How frequently do you make a release?

Nightly

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @kanglant :wave:
For a nightly project, I don't believe it's too critical to keep the old versions. You are releasing every night after all, otherwise you will be the larger project on PyPI with a 1.2G daily release.
Have you consider setting up a custom PyPI index in your infra so people can get the daily snapshots of your project?

**Comment by kanglant** [comment]
Hi @cmaureir ,

Thank you for your suggestion! We want to maintain at least one month's history of TF-TPU nightly packages on PyPI because we currently lack comprehensive unit tests to catch all potential bugs before release. We mainly rely on end-to-end model testing. Unfortunately, nightly tests can fail due to various factors, such as TF-libtpu mismatch, VM image workflow issues, insufficient TPU capacity, bugs in other TF components, and libtpu bugs. Each of these issues requires time to fix. By the time we identify an error, it may be too late because we need to back track and identify when it starts breaking.  

We've successfully reduced the size of a single wheel to 220 MB. Therefore, could you please approve our request to increase the project limit to >27 GB? We appreciate your understanding and support.

**Comment by rgommers** [comment]
> Have you consider setting up a custom PyPI index in your infra so people can get the daily snapshots of your project?

@kanglant if you get asked a question like this by an admin, it's helpful for moving the process forward if you answer it. The question is very much valid. Please have a look at https://pypi.org/stats/ and see the incredible amount of space that TensorFlow takes up on PyPI. _10 out of 15 of the top space-consuming packages are flavors of TensorFlow!_ This has historically been approved (I have no insight into why, but my guess is because Google is a PyPI infra sponsor), but it's not a great situation.

All other projects I know of which publish nightlies and have large wheels (PyTorch, JAX, NumPy, SciPy, Matplotlib, etc.) do this _outside of PyPI_. Here is an example of what your Google colleagues from the JAX project do: https://jax.readthedocs.io/en/latest/installation.html#nightly-installation. Publishing many types of nightlies of this size to PyPI will, by at least a part of the community, be seen as abuse of the system. Given that PyPI space constraints are real, taking up such a large amount of space detracts from the more valid limit requests submitted by other projects for their regular releases. I strongly recommend you reconsider what you're doing here.

**Comment by rgommers** [comment]
> We want to maintain at least one month's history

Another thing that would really help is actually follow through on this (or maybe 2 months or another reasonable period) for all your nightlies. https://pypi.org/project/tf-nightly-intel/#history contains nightlies that are >1.5 years old, and this package takes up 300 GB (second highest across all of PyPI)!

Same for https://pypi.org/project/tf-nightly-cpu-aws/#history, not cleaned up since June 2022 and taking up ~240 GB. You could clean up many hundreds of GBs of nightlies pretty easily.

**Comment by MichaelHudgins** [comment]
>  incredible amount of space that TensorFlow takes up on PyPI. _10 out of 15 of the top space-consuming packages are flavors of TensorFlow!_ This has historically been approved (I have no insight into why, but my guess is because Google is a PyPI infra sponsor), but it's not a great situation.

There are historical aspects as to why TensorFlow takes up so much space and while I don't think anyone argues it is ideal, it is beneficial to have it be available directly on pypi and not through a secondary index. 

> All other projects I know of which publish nightlies and have large wheels (PyTorch, JAX, NumPy, SciPy, Matplotlib, etc.) do this _outside of PyPI_. Here is an example of what your Google colleagues from the JAX project do: https://jax.readthedocs.io/en/latest/installation.html#nightly-installation. Publishing many types of nightlies of this size to PyPI will, by at least a part of the community, be seen as abuse of the system. 

I am not sure why this would be considered abuse of the system, they are large but we do limit them to the last 90 for tf-nightly and tf-nightly-cpu.  Looking into moving nightlies to an index is something that can be considered, but for this particular request it would be good if in the mean time we can get the approval for the additional space to ensure a uniform experience across installing TensorFlow and its nightlies. 

> Another thing that would really help is actually follow through on this (or maybe 2 months or another reasonable period) for all your nightlies. https://pypi.org/project/tf-nightly-intel/#history contains nightlies that are >1.5 years old, and this package takes up 300 GB (second highest across all of PyPI)!
Same for https://pypi.org/project/tf-nightly-cpu-aws/#history, not cleaned up since June 2022 and taking up ~240 GB. You could clean up many hundreds of GBs of nightlies pretty easily.

Those builds are not published by the TF DevInfra team and rather by partners.  We will bring it to their attention and look to have them remove older nightlies like the official tf-nightly does.

CC: @di who also may have more context to the historical aspects you mention here.

**Comment by rgommers** [comment]
> it is beneficial to have it be available directly on pypi and not through a secondary index.

Sure, of course it is. That is true for every project though.

> I am not sure why this would be considered abuse of the system

Note that I'm not an admin and I don't have insight into the history here. It's very well possible there is some arrangement that makes allowing only TF to upload large nightlies a win-win for both TF and PyPI (and hence for the community). All I know is that it's generally not approved because it puts too large a load on PyPI. The README of this repo has guidelines that say:

```
Upload limits are generally denied for the following reasons:

- project makes nightly releases and/or is published frequently
```

There's also an active discussion on the packaging Discourse about the backlog in requests on this repo, and that there are too many requests and tasks for the current folks with admin rights.

> Those builds are not published by the TF DevInfra team and rather by partners. We will bring it to their attention and look to have them remove older nightlies like the official tf-nightly does.

Thank you! That would be quite helpful.

**Comment by di** [comment]
I've set the total size limit for `tf-nightly-tpu` to 40GB on PyPI.
