### ISSUE TITLE
File Limit Request: chromiumfile - 500 MB

### ISSUE THREAD

**Issue by lcctoor** [pypi/support#3269]
### Project URL

https://pypi.org/project/chromiumfile/

### Does this project already exist?

- [X] Yes

### New Limit

500 MB

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

#### Project Purpose
This project is a Chromium browser package, offering Python users a convenient way to download the Chromium browser.

The version number of this package will align with the version number of the Chromium browser. For example, the chromiumfile package containing Chromium version '100.2.3' will also have the version number '100.2.3'.

#### Duration of Operation
This is a newly created project, released for less than 2 hours.

#### Attempts Made
I've tried compressing the files with the highest compression rate, but the size still exceeds 100MB.

### Reasons for the request

The idea originated when I was developing a Python version of the Electron framework, which relies on the Chromium browser. I suddenly realized the necessity of publishing the complete Chromium files on PyPI, for the following reasons:

#### Chromium Becoming a Common Essential Tool in Python Development
Many popular projects, such as pyppeteer, selenium, and others rely on Chromium. I anticipate that more projects will require it in the future.

#### Integrating Chromium on PyPI Simplifies Program Logic
Many packages that depend on Chromium download it from various storage sources. The reliability of these diverse storage sources can be an issue, and even the content of the Chromium files might differ from one source to another. This means that these projects have to address their respective problems in code, and many of these problems are repetitive. This results in many Python developers doing redundant work. Having a universal Chromium interface on PyPI that pre-resolves many of these issues will reduce the development cost for many developers.

#### Publishing Chromium on PyPI Increases Program Security
The security of projects on PyPI is overseen by a broad user base. However, if a Python package relies on a Chromium downloaded from a custom external source, its security becomes uncertain.

### How large is each release?
400~500MB

### How frequently do you make a release?
Every six months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by lcctoor** [comment]
Additional:
# How large is each release?
200~300MB

# How frequently do you make a release?
Every six months.

**Comment by cmaureir** [comment]
Hey @lcctoor :wave:
It seems that you only need the users to have a chromium version downloaded/installed. Have you explored other ways to distribute your package?
NLTK has a nice option to download the data, which in your case you could offer in case chromium is not found: https://www.nltk.org/data.html

**Comment by lcctoor** [comment]
Dear PyPI team,

Firstly, I want to express my gratitude for your response to my proposal. However, I must candidly admit that I was somewhat taken aback by the recommendation to use NLTK's data download method.

The NLTK approach is primarily designed for smaller natural language processing datasets and models, whereas Chromium is a large-scale software where integrity is paramount. Given the significant differences between the two, the NLTK method seems ill-suited for my project.

I fully understand the intention behind suggesting alternate solutions, but I hope you can delve deeper into the actual needs of our project. My goal is to offer the Python community a straightforward, secure, and reliable channel to download Chromium. I genuinely hope to gain the support of PyPI, so we can bring more conveniences to Python developers at large.

I look forward to your further response and greatly appreciate your time and consideration.

**Comment by pradyunsg** [comment]
Hi @lcctoor!

> Firstly, I want to express my gratitude for your response to my proposal.

And, likewise -- most of us triaging on this issue tracker are volunteers, and we appreciate the kind words, that you're responding in an amicable tone, and your patience here! :)

> This project is a Chromium browser package, offering Python users a convenient way to download the Chromium browser.

Quoting from our documented policy from the README in this repository:

> Upload limits are generally denied for the following reasons:
> - [skipping other bullets]
> - project includes a large JAR file / executable

I believe that shipping Chromium would certainly qualify for that, which is why (I think) @cmaureir asked if you'd explored shipping that separately.

> I hope you can delve deeper into the actual needs of our project

Looking into this one more closely, I agree that NLTK is not be a 1:1 example in this case but the underlying suggestion is still sound IMO. However, I do think that underlying suggestion (of separating the Chromium distribution from the Python code) is still a sound one.

There's precedence for projects which rely a compiled-in-a-specific-manner browser distribution, _and_ distributing them via a separate channel than the Python code itself (a handy example is https://playwright.dev/python/docs/browsers).

Have you explore doing something similar, i.e. hosting the actual Chromium binaries separately from the Python code, and providing a mechanism to fetch them prior to use via the Python API?

**Comment by di** [comment]
Closing due to lack of response.
