### ISSUE TITLE
File Limit Request: sourcery-nightly - 200 MB

### ISSUE THREAD

**Issue by brendanator** [pypi/support#3337]
### Project URL

https://pypi.org/project/sourcery-nightly

### Does this project already exist?

- [X] Yes

### New Limit

200 MB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI, TestPyPI

### About the project

Sourcery is a IDE extension and CLI tool for reviewing Python code and suggesting refactorings to improve the quality of that code.

The [sourcery-nightly](https://pypi.org/project/sourcery-nightly) package contains nightly builds for the [sourcery](https://pypi.org/project/sourcery) package

### Reasons for the request

We recently had the an [increase to 200 MB approved for the sourcery project](https://github.com/pypi/support/issues/3024)

Now we'd like our nightly builds to be able to increase too please

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by pradyunsg** [comment]
Quoting from the README, which describes how we handle these tickets:

> Upload limits are generally denied for the following reasons:
>
> - project makes nightly releases and/or is published frequently

Since the requested increase is a small one, I'm going to go ahead and increase the limit as requested in this case.

Please be mindful that there is a project-wide limit of 10 GB that likely won't be raised for a project that has nightly releases.
