### ISSUE TITLE
File Limit Request: triton - 500 MB

### ISSUE THREAD

**Issue by ptillet** [pypi/support#3430]
### Project URL

https://pypi.org/project/triton/

### Does this project already exist?

- [X] Yes

### New Limit

500

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

Triton is a language and compiler for writing custom deep learning kernels. It is a core dependency of `pytorch` since version 2.0, and has become an important target for many GPU hardware vendors (nvidia, amd, intel).

### Reasons for the request

As we add more targets and integrate them in the standard distribution, the size of the wheels that we release -- including all possible targets -- also becomes bigger. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by rgommers** [comment]
@ptillet for limit requests, especially large ones, it tends to be helpful to give as much detail/justification as possible. I had a look at this now, which is hopefully helpful for the PyPI maintainers:

- Triton 2.0.0 (Mar'23) had wheels of ~63 MB
- Triton 2.1.0 (Sep'23) had wheels of ~89 MB
- Size is growing quite quickly at the moment however, the latest manylinux nightlies (from the index server as documented in https://triton-lang.org/main/getting-started/installation.html) weigh in at ~168 MB

So it looks like a file size limit of 200 MB or 250 MB would be enough for your next release. However, since these limit requests take time to process, asking for more makes sense if you see the current growth continuing.

You're probably also going to need a total size limit increase soon? 8 wheels may be close to 2 GB per release soon, and if you're really getting close to 500 MB per file that the total project space usage of 10 GB will be gone in 2 releases.

**Comment by ptillet** [comment]
Thanks for your reply! You are correct that we expect 2.2 release to be 160MB. We also have plans in the works to reduce wheel size in the next few months, but this will be counterbalanced by native AMD and Intel support.

I am fine with requesting an increase to 250MB for now, since there is a chance this could be enough even for future releases

**Comment by rgommers** [comment]
Thanks @ptillet - 250 MB looks reasonable and necessary to me.

**Comment by cmaureir** [comment]
Hey @ptillet :wave:
following your last comment,  I've set the upload limit for `triton` to 250 MB on PyPI. Please be mindful of the frequency of releases at that size as mentioned by @rgommers 
have a nice weekend :tada:
