### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kamilodev** [pypi/support#3562]
### PyPI Username

kamilodev

### Reason for request

I lost my phone with authenticator app and recovery codes, this is my website, kamilodev.dev, my email, kamilo@kamilodev.dev, and the same github user, X, I mean, I use the same user in all my accounts, please help me to recover my user. Thank you very much

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
