### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ipseityperse** [pypi/support#3566]
### PyPI Username

mortemphilia

### Reason for request

I posted a package that was harmless but demonstrated a supply chain kind of attack.
The package has a clear readme stating not to install it and what it did if installed.
My account seems to be blocked now - is it possible to recover it?

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by ewdurbin** [comment]
Oh also we do not re-instate malicious actor accounts.
