### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cipherswami** [pypi/support#3571]
### PyPI Username

name-is-cipher

### Reason for request

Lost my 2FA device

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by cipherswami** [comment]
@ewdurbin Can you please reset my 2FA little quicker, its been 3 days now.

**Comment by tarekziade** [comment]
@cipherswami some of us have been waiting for over 4 months. So you will have to be very patient. Some context https://discuss.python.org/t/pypi-account-recovery-process-triaging-on-halt/43422/76

**Comment by cipherswami** [comment]
@tarekziade 🥲 Noice !!! 

Its better to create new account with secondary Gmail, I too still prefer with my main account though. 
Any ways 👍🏻

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.
