### ISSUE TITLE
PEP 541 Request: dojo

### ISSUE THREAD

**Issue by verbose-void** [pypi/support#3587]
### Project to be claimed

`dojo`: https://pypi.org/project/dojo

### Your PyPI username

`Dyllan`: https://pypi.org/user/Dyllan

### Reasons for the request

at quilter, we're looking to release a set of reinforcement learning algos of which we have many. especially for our future paper publications. the `dojo` project can't be found. i couldn't find any owning user and got this error while trying to upload code to the pypi project: 

```
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         The user 'Dyllan' isn't allowed to upload to project 'dojo'. See https://pypi.org/help/#project-name for more
         information.
```

after looking further, none of the steps for reaching out to a user was possible. so i created this issue.

### Maintenance or replacement?

None

### Source code repositories URLs

code is currently private, we were looking to reserve to roll out over 2024.

### Contact and additional research

it doesn't appear to be owned by anyone, as the project simply doesn't exist when following the link. i was thinking maybe it's because of the dojopy project might be too similar.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by verbose-void** [comment]
Okay, thank you for your response.

**Comment by Thespi-Brain** [comment]
Hi @verbose-void,

The Owner of the project has responded back and intends to keep working on their project and push a release within the week. Since that's the case, unfortunately, the project name "dojo" cannot be transferred to you. I will still keep this issue open just in case the owner has not pushed a release and will make a recommendation to PyPI admins accordingly.

**Comment by Thespi-Brain** [comment]
Hi @verbose-void,

The owner of the project has informed me that they have actively added new functionality to their project quite recently. Since they are continuing to work on this project, per [PEP 541 guidelines](https://peps.python.org/pep-0541/#reachability), the project name "dojo" cannot be transferred to you. I would suggest going with a different name for your project, thank you.

**Comment by verbose-void** [comment]
ok, thank you for your messages.
