### ISSUE TITLE
Project Limit Request: PyArrow - 25 GB

### ISSUE THREAD

**Issue by amoeba** [pypi/support#3717]
### Project URL

https://pypi.org/project/pyarrow

### Does this project already exist?

- [X] Yes

### New limit

25GB

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

From the description on PyPi:

> This library provides a Python API for functionality provided by the Arrow C++ libraries, along with tools for Arrow integration and interoperability with pandas, NumPy, and other software in the Python ecosystem.

PyArrow has been active since 2017.

### How large is each release?

Source: ~1 MiB
Binaries: ~1200 MiB (Windows, macOS, Linux, CPython 3.{8,9,10,11 12})

I put in a request of 25GB just to give our project headroom but if more can easily be given, that might be helpful.

### How frequently do you make a release?

Once every 3 months.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hey @amoeba  :wave: 
I've set the project limit for `pyarrow` to 25 GB on PyPI. Please be mindful of the frequency of releases at that size, and maybe consider using the [Limited API](https://docs.python.org/3/c-api/stable.html) in order to reduce the amount of wheels per each release. 

Have a nice end of the week :tada:

**Comment by amoeba** [comment]
Thanks for the quick help @cmaureir! I'll have a look at https://docs.python.org/3/c-api/stable.html.

**Comment by raulcd** [comment]
Thanks @cmaureir for the quick response!
