### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fcrozetta** [pypi/support#3739]
### PyPI Username

`fcrozetta`

### Reason for request

- Lost access to 2FA
- Lost recovery codes.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by fcrozetta** [comment]
Hi @ewdurbin , How are you doing? I saw you are handling the Recoveries. 
Would you kindly initiate the conversation via the main email in my account, or let me know if I need to start it from my side to a specific email?

Thanks for your support :)

**Comment by ewdurbin** [comment]
Because there are no projects associated with this account, 2FA has been reset and a password reset issued, you should be able to regain access to your account after completing the password reset.

PyPI now supports generating 2FA recovery codes, please read more [here](https://pypi.org/help/#recoverycodes) to generate and store recovery codes for your account.

**Comment by fcrozetta** [comment]
@ewdurbin Thank you a lot!
Have a great day!
