### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ACharbonneau** [pypi/support#3830]
### PyPI Username

`cdadevteam`

### Reason for request

Lost access to 2FA app. Our dev left suddenly and it did not get transfered to someone else on our team. Our project is here: https://github.com/CancerDataAggregator Thanks

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by abradyGDIT** [comment]
Assuming anyone's listening and also assuming there's anything that can be done short of continuing to wait, if there's any way to expedite this request, please point us to information on how -- right now we have live, public-facing software that we can't release via PyPI because of our administrative error during a staff transition (described in the initial request).

Our team at the National Cancer Institute is deeply grateful in advance for anything anyone can suggest that might move this recovery process forward soonish.

**Comment by Thespi-Brain** [comment]
Hi @ACharbonneau,

Apologies for the tardiness in our response. We are doing some research to best proceed with the next course of action regarding account recovery. We will get back to your shortly. Thanks!

**Comment by ACharbonneau** [comment]
Thank you!

**Comment by Thespi-Brain** [comment]
Hi @ACharbonneau,

Please contact support@pypi.org with an email address that you would like this account to be associated with and please reference this support link as well https://github.com/pypi/support/issues/3830. We will proceed from there, thanks!

**Comment by Thespi-Brain** [comment]
Hi @ACharbonneau and @abradyGDIT,

Thanks for confirming your new preferred email address. I have updated and reset your account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
