### ISSUE TITLE
File Limit Request: CTranslate2  - 300 MB

### ISSUE THREAD

**Issue by minhthuc2502** [pypi/support#3870]
### Project URL

https://pypi.org/project/ctranslate2/

### Does this project already exist?

- [X] Yes

### New Limit

300

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

This is a C++ and Python library for efficient inference with Transformer models. It has been active sine 2018. It is one of most powerful framework for the inference of Transformer models.

### Reasons for the request

After adding the new feature ``Flash Attention 2`` from this [repo](https://github.com/Dao-AILab/flash-attention), The package become heavier. I can't optimize much the size of package because this is the integration of the kernel from original repo. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by BBC-Esq** [comment]
Please allow this limit increase ASAP!  This is a great library and is worthy of it.  Also, @minhthuc2502 is it possible for me to host the wheels somehow.  I'd be willing to build the windows ones if you'll show me.  Thanks!

**Comment by cmaureir** [comment]
Hey @minhthuc2502 :wave:
I've set the upload limit for `ctranslate2` to 300 MB on PyPI. Please be mindful of the frequency of releases at that size, you might reach the project limit soon.
Have you explore other ways to reduce the size of the packages? complementary, you could study the possibility to use the Limited API https://docs.python.org/3/c-api/stable.html in order to reduce the amount of wheels.
Have a nice day :rocket:

**Comment by minhthuc2502** [comment]
I appreciate  your quick reply. Thank you very much.
Have a nice day.
