### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kuanysh-beisembayev** [pypi/support#3882]
### PyPI Username

kuanysh.beisembayev

### Reason for request

Can not sign in to my account even after password reset

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @kuanysh-beisembayev,

We are doing some further research on your account recovery request to determine best next steps to proceed. We will get back to you shortly. Thanks.

**Comment by Thespi-Brain** [comment]
Hi @kuanysh-beisembayev,

In order to initiate the account recovery process, a project needs to have public repos. I did not see any public repos associated with your account. I also noticed that the projects associated with your account have an additional owner. If you would like, we can have your projects just have one owner, initiate the recovery process, and once that's done, the additional owner can be re-added upon request. Please let us know how you would like to proceed. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @kuanysh-beisembayev,

I am following up regarding your request. Are you still having an issue regarding logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
