### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by marcelo-smartup** [pypi/support#3927]
### PyPI Username

marcelo-smartup

### Reason for request

I lost access to my 2FA authentication app :(

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @marcelo-smartup,

I took a look at your account, and in order for us to initiate an account recovery process, we need to have public repos of your project connected to your account. Otherwise, it's a seven day waiting period before your 2FA and account access is reset. It is part of our security measures. Let us know how you would like to proceed. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @marcelo-smartup,

I am following up regarding your request. Are you still having an issue regarding your 2FA and logging in? Let us know! I will keep this issue open for another week unless I hear from you earlier. After that, if you are still having trouble, feel free to create a new request. Thanks!

**Comment by Thespi-Brain** [comment]
Closing due to non response.
