### ISSUE TITLE
Account deletion request (TestPyPI)

### ISSUE THREAD

**Issue by phillippe** [pypi/support#4207]
### PyPI Username

phillippea

### Reason for request

I accidentally set the primary email to an old email I lost access to instead of my new one. I've already made a new account with the correct email, but I can't delete this one because I can't verify the email.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @phillippe,

We generally don't delete accounts on behalf of users. One way we can resolve your issue is if you have another email address that is different from your primary email address in your test.pypi account and also different from the correct email address you used for your second test.pypi account, we can update the account with that third email address so that you can have access and you can choose to delete it yourself if you so wish. Let me know how you would like to proceed. Thanks!

**Comment by phillippe** [comment]
I managed to recover my old email and deleted the account already. Thanks!
