### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by johningve** [pypi/support#4300]
### PyPI Username

`zivid`

### Reason for request

Lost 2FA authentication app or security token and recovery codes as well. Have access to email and password.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by johningve** [comment]
In case it helps with verification, we added a notice on our repository: https://github.com/zivid/zivid-python

**Comment by Thespi-Brain** [comment]
Hi @johningve,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Since the link to the public repo to your project was not connected to the account (only the website of zivid was linked), once you receive the instructions, please use the public repo for zivid to complete the instructions. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @johningve,

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
