### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by dse0** [pypi/support#4348]
### PyPI Username

`dse`

### Reason for request

The 2FA set up on my PyPi account uses a physical Yubikey. I still have the yubikey but it has been damaged and no longer functions. It appears I never created recovery codes for this account so I am now locked out. I still have access to my email address (dan@hashboard.com) and my API token. Thank you for your help!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @dse0,

In order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. Unfortunately, when I took a look into your account, there was no such active link. 

What I can offer as a workaround is for you to send an email to support@pypi.org confirming your intent to reset your 2FA and recovery codes with a link to this issue (https://github.com/pypi/support/issues/4348). There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @dse0,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
