### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by oaubert** [pypi/support#4481]
### PyPI Username

`OlivierAubert`

### Reason for request

Hi. I do not have access anymore to the primary email address olivier.aubert@liris.cnrs.fr (university lab I quit long time ago) for the account OlivierAubert. My primary email address is contact@olivieraubert.net, which is also linked to another pypi account (username `oaubert`). The cleanest way I see would be to delete the oaubert pypi account (which is not used) and change the primary email for OlivierAubert to contact@olivieraubert.net. If necessary, it is also possible to keep both accounts and use the alias olivier@olivieraubert.net for the OlivierAubert account.
Thanks!

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @oaubert,

Since we only allow one unique email address per one unique account, I think the "cleanest" way will be to disassociate the primary email for your other account if you wish to use it for the "OlivierAubert" account.  We do have an account verification as due diligence before we can update your email. So, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/4481). We will proceed from there. Thanks!

**Comment by oaubert** [comment]
Is the procedure stuck at some point, or should I do something (beside sending the mail, which has been done)?
