### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by kelleyk** [pypi/support#4498]
### PyPI Username

`Kevin.Kelley`

### Reason for request

I don't have access to the email address associated with this account any longer.   I haven't used the `Kevin.Kelley` account in a long time; if possible, I'd like to add my more current account (`kelleyk`) as an owner of the projects that `Kevin.Kelley` owns.

I'm trying to regain access to those projects because another engineer recently reached out to ask if I could give him one of the project names that I wound up registering but never using.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @kelleyk,

I think the best way to resolve your issue would be to send over a new, unique email address that you have access to so that we can update it for the "Kevin.Kelley" account. That way, after you have access, you can transfer ownership of projects yourself to your newer account. 

Please contact support@pypi.org with an email address that you would like the account to be associated with and please reference this link (https://github.com/pypi/support/issues/4498). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @kelleyk,

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
