### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by MartinSalinas98** [pypi/support#4667]
### PyPI Username

GigabitClowns

### Reason for request

Created account with an email I don't own (due to a typo).

I need deletion of the non-verified account.

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @MartinSalinas98,

We don't delete accounts on behalf of users since we like to give users agency over their own accounts. If you want to login so that you can access the account and do what you wish with it, you can send us an alternate email address that you would like for this account to support@pypi.org with a link to this issue(https://github.com/pypi/support/issues/4667). We will go from there, thanks.

**Comment by MartinSalinas98** [comment]
Email sent, thanks!

**Comment by Thespi-Brain** [comment]
Hi @MartinSalinas98,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
