### ISSUE TITLE
Unable to verify email for 'deltares' pypi account

### ISSUE THREAD

**Issue by rooije** [pypi/support#4701]
Dear PyPi,

We are running into a problem regarding a PyPi account named ‘deltares’ that is linked to email address [Tjerk.vreeken@deltares.nl](mailto:Tjerk.vreeken@deltares.nl).

The problem is that we can login to PyPi but we do not have the means to Verify the email as the email address has been closed and cannot be opened due to privacy issues. This make our ‘deltares’ pypi account unusable.

Is there a way you can assist?

Thanks,

Erik de Rooij
Sr. Adviseur/onderzoeker

T    +31 883358235
M   +31 646424072
E   [erik.derooij@deltares.nl](mailto:erik.derooij@deltares.nl)

**Comment by miketheman** [comment]
Please see https://pypi.org/help/#account-recovery for the options

**Comment by Thespi-Brain** [comment]
Hi @rooije,

Since the previous email address is unreachable, we would need a new email address associated with this account to start the account verification process and give you all access. Please contact support@pypi.org with an email address that you would like the account to be associated with and please reference this link (https://github.com/pypi/support/issues/4701). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @rooije,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by rooije** [comment]
Dear support,

I have received the email to initiate account recovery. One of my colleges (Marnix.Kraus@deltares.nl) performed the branch operation under his email. I hope this is not a problem as did not have access to the suggested repository.

Regards,

Erik de Rooij

**Comment by rooije** [comment]
Dear support,

Is there any update on this issue?

Thanks,

Erik de Rooij

**Comment by Thespi-Brain** [comment]
Hi @rooije,

You provided us with your email address in order to proceed with the account verification. Your colleague cannot use their email address to push the branch. That completely defeats the purpose of account verification. 

If you don't have access to the repo linked to the PyPI account, then what I can offer as a workaround is for you to send an email to support@pypi.org confirming your intent to reset your 2FA and recovery codes with a link to this issue (https://github.com/pypi/support/issues/4701). There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @

Thanks for completing the verification process. The verification was successful! I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues.
