### ISSUE TITLE
File Limit Request: deeplake & libdeeplake - 50GB

### ISSUE THREAD

**Issue by davidbuniat** [pypi/support#4818]
### Project URL

https://pypi.org/project/libdeeplake/

### Does this project already exist?

- [X] Yes

### New Limit

50000

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

We are shipping deeplake (https://github.com/activeloopai/deeplake) backend binary named as libdeeplake

Total size ~200MB (single wheel size 10-20MB)

### Reasons for the request

Previously you have kindly bumped to 20GB which we highly appreciate https://github.com/pypi/support/issues/3238, currently we reached another limit despite us cleaning up previous releases and working to make the release version smaller.It is quite important to keep previous versions for our users to reproduce their data processing. 

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @davidbuniat :wave:
I've set the project limit for `libdeeplake` to 50 GB on PyPI. 
Please try to find ways of distributing the package in the future with a different approach, or consider removing the old-unused releases, because going over 50G might need a stronger justification.
Have a nice week!
