### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by wades-altair** [pypi/support#4834]
### PyPI Username

`csi-python`

### Reason for request

Lost access to email address

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @wades-altair,

Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/4834). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @wades-altair,

Thanks for sending over your preferred email address. However, in order to start the account recovery process to reset your 2FA and recovery codes (which also includes updating your email address), your account needs to have a valid/active link to a public repo of your project. Unfortunately, when I took a look into your account, there was no such active link. 

What I can offer as a workaround is for you to send an email to support@pypi.org confirming your intent to reset your 2FA and recovery codes with a link to this issue (https://github.com/pypi/support/issues/4834). There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

**Comment by wadesathome** [comment]
Apologies I have not sent this yet -- I think I was confused by some email threading. Let me get to this now. Thanks.

**Comment by wades-altair** [comment]
Hello -- apologies, I have only just sent this email. I will keep a look out so that I can reset the 2FA and recovery codes in a timely fashion after the account is reset. Thanks!
