### ISSUE TITLE
Project Limit Request: Euphorie - 10 GB

### ISSUE THREAD

**Issue by ale-rt** [pypi/support#4995]
### Project URL

https://pypi.org/project/Euphorie/

### Does this project already exist?

- [X] Yes

### New limit

12

### Update issue title

- [X] I have updated the title.

### Which indexes

PyPI

### About the project

I hope that 2 additional GiB and some changes to the static resource distribution will allow us to be able to not reach the limit for the foreseable future.

### How large is each release?

As of today, each release is ~180 MiB (90MiB source dist + 90 MiB wheel). In the release we bundle some static resources.
We understand that it is better to not bundle them with code and will change this in the future.

### How frequently do you make a release?

The order of magnitude is more or less a dozen/year

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @ale-rt :wave:
You have an inconsistency on the title (10G) and what's inside the issue (12G), please try to take care of this otherwise we will unable to know which of the two is the requests.
In this particular case, since 10G is the default, I assumed you requested 12G, so I have just updated the project limit for `euphorie` on PyPI, I hope it was right.
Have a nice week!

**Comment by ale-rt** [comment]
> Hello [@ale-rt](https://github.com/ale-rt) 👋 You have an inconsistency on the title (10G) and what's inside the issue (12G), please try to take care of this otherwise we will unable to know which of the two is the requests. In this particular case, since 10G is the default, I assumed you requested 12G, so I have just updated the project limit for `euphorie` on PyPI, I hope it was right.

Thanks a lot, you got that right!

> Have a nice week!

You too, best wishes and thanks again!
