### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by richetl** [pypi/support#5038]
### PyPI Username

`opensource_ni`

### Reason for request

The person whose authenticator was associated with this account has left the company. I was able to get the email address rerouted, and now have control of that. However, when the 2FA check came up I realized that we at NI do not have possession of that device. Any help on this front would be appreciated.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @richetl,

We can definitely do an account recovery process so that your account's 2FA and recovery codes are reset. However, I noticed that the new primary email address is bouncing. Is there another company/common email address we can use for your account? Please contact support@pypi.org with an email address that you would like your account to be associated with and please reference this link (https://github.com/pypi/support/issues/5038). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @richetl,

Thanks for sending over your preferred email. I have initiated an account recovery process and instructions are being sent to your preferred email address. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @richetl,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
