### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by travisgk** [pypi/support#5072]
### PyPI Username

`travisgk` 

### Reason for request

The GitHub email system is causing me a lot of issues. Could you change my email one more time please? Or preferably just delete my entire account so I can restart this process.

I used 162270915+travisgk@users.noreply.github.com, please change this to:
githubtravisgk@gmail.com

I'm hoping someone can manually change the email to the correct one so I can verify the address. Thank you for your time. I cannot get into my account at all because I can't even use the password reset. If you run into any issues, just delete my entire account.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @travisgk,

We don't delete user accounts because we want to give the users agency over their own accounts. Since we do have an account verification as due diligence before we can update your email, please contact [support@pypi.org](mailto:support@pypi.org) with your preferred email address and reference this link (https://github.com/pypi/support/issues/5072). We will proceed from there. Thanks!

**Comment by Thespi-Brain** [comment]
Hi @travisgk,

I have updated the primary email address on the account. Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
