### ISSUE TITLE
File Limit Request: llama-cpp-cffi - 600 MB

### ISSUE THREAD

**Issue by mtasic85** [pypi/support#5186]
### Project URL

https://pypi.org/project/llama-cpp-cffi/

### Does this project already exist?

- [x] Yes

### New Limit

600

### Update issue title

- [x] I have updated the title.

### Which indexes

PyPI

### About the project

Python binding for [llama.cpp](https://github.com/ggerganov/llama.cpp) using cffi. Supports CPU, Vulkan 1.x and CUDA 12.6 runtimes, x86_64 and aarch64 platforms.

### Reasons for the request

We have applied aggressive compression already. Since `llama.cpp` project which is being wrapped increased size once compiled, we need to follow that size as well. We managed to get it under 450-500 MB, so new limit of 600 MB would be enough.

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

**Comment by cmaureir** [comment]
Hello @mtasic85 :wave:
I've set the upload limit for `llama-cpp-cffi` to 600 MB on PyPI, but please consider other ways of distributing the binaries in your wheel in order to avoid having a huge wheel distributed for users, this is an exception because I usually don't assign more than 500M to projects.
Also, consider checking the Python Limited API https://docs.python.org/3/c-api/stable.html to avoid having one-wheel-per-python-version.
Have a nice week :wave:
