### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Rhiannon-Udall** [pypi/support#5189]
### PyPI Username

`rhiudall`

### Reason for request

I am have lost access to the 2FA authentication app. 

In the past 6 months I have had to replace both my laptop (where I would have stored recovery codes) and my phone (which was my 2FA device) and did not manage the data transfer well. 

I *do* still  have access to my email address, and I also did successfully store the token for a specific project (the updating of which was my immediate goal, so I have just pushed that update). 

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @Rhiannon-Udall,

In order to start the account recovery process to reset your 2FA and recovery codes, your account needs to have a valid/active link to a public repo of your project. Unfortunately, when I took a look into your account, there was no such active link. 

What I can offer as a workaround is for you to send an email to support@pypi.org confirming your intent to reset your 2FA and recovery codes with a link to this issue (https://github.com/pypi/support/issues/5189). There will be a 7 day wait period from that email as part of our verification/security policy, after which we will go ahead and reset your account and go from there. Thanks!

**Comment by Rhiannon-Udall** [comment]
Thank you for the update, I have sent that email now!

**Comment by Thespi-Brain** [comment]
Hi @Rhiannon-Udall,

Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.
