### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by ACE07-Sev** [pypi/support#5324]
### PyPI Username

A.C.E07

### Reason for request

Greetings there,

Hope all are well. I think I have lost my 2FA authentication app (I imagine it was on my old phone). I would like to get access back.

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment]
Hi @ACE07-Sev,

I have initiated an account recovery process and an email is being sent to the primary email address associated with your account. Please follow the instructions in that email and reply to it, and we will go from there. Thanks!

**Comment by ACE07-Sev** [comment]
@Thespi-Brain Greetings,

I followed the instructions, and made the branch you requested, but have not heard back from your side yet. I have to publish a package soon, hence I'd deeply appreciate the prompt response.

**Comment by Thespi-Brain** [comment]
Hi @ACE07-Sev,

We work regular business hours, not on the weekends, and since your email was sent during the weekend, we were not able to get to it until now. 

Thanks for completing the verification process. The verification was successful! Your 2FA has been reset and a password reset has been issued. You should be able to regain access to your account after completing the password reset. Let us know if you have any more issues. Thanks.

**Comment by ACE07-Sev** [comment]
Greetings,

Hope you are well. I see, my apologies for the inconvenience. Immensely (I
mean it) grateful for the prompt response.

Thank you again, and I wish the best of holidays!

Sincerely yours with best regards,
Amir Ali
